version: '3.3'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - Mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
          
  apache:
    image: apache2
    depends_on:
      - db
    ports:
      - 3333:80
