version: '3.3'
services:
  db:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    restart: always
    volumes:
      - Mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_USER: ChiefCommander
      MYSQL_PASSWORD: ChiefCommander
    
  apache:
    image: apache2
    depends_on:
      - db
    ports:
      - 3333:80

volumes:
  Mysql:
