version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./Mysql:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
          
  apache:
    build: Apache/.
    depends_on:
      - db
    links:
      - db
    ports:
      - 3333:80
